# Generated by Django 2.1.5 on 2019-02-11 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomlocator', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('room', 'period')},
        ),
    ]
