# Generated by Django 2.1.5 on 2019-02-12 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomlocator', '0002_auto_20190212_0054'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('block', 'number')},
        ),
    ]
